### PR TITLE
Finish renaming gem to circumstance

### PR DESCRIPTION
**Pull request by mikeastock**

### CODE REVIEW

**Comment by seanarnold** [comment]
👍

**Comment by mikeastock** [comment]
Bump @Oneill38

**Review by Oneill38 — APPROVED** [review]

**Comment by mikeastock** [comment]
@Oneill38 down to merge it?

**Comment by Oneill38** [comment]
@mikeastock ahh yes, totes forgot you probably can't merge it. 👍

**Comment by mikeastock** [comment]
Haha yep I can’t merge! Thanks!

**Pull request merged**
